### ISSUE TITLE
self:GetBanner():ShowText() not showing at all on smaller scenes

### ISSUE THREAD

**Issue by Bebomonky** [cortex-command-community/Cortex-Command-Community-Project#109] opened 2024-02-21 23:56 UTC
**Describe the bug**
Attempting to try to use **self:GetBanner():ShowText()** on smaller scenes causes the text not to appear at all (not even in a frame)

**To Reproduce**
1. A scene with a size of 1584 x 1200 (and smaller ones apply aswell)
2. Use showtext in a update function (this should cause it to constantly appear for debugging I guess)

**Expected behavior**
No text appearing, at all, there is no way to indicate that it actually shows since it doesn't no matter what

**Additional context**
- enable VSync (off)
- fullscreen (off)
- Use Multiple Displays (off)
- Resolution: 1280 x 720 (2x fullscreen scale) + Scale to Fullscreen
- Version: 6.2.1

**Comment by MyNameIsTrez** [comment] 2024-02-22 00:04
Important to mention that bebo sees it did work in a release 6 development build

**Comment by Causeless** [comment] 2024-02-22 02:27
Closing- issue was caused by mod accidentally disabling GUI

**Closed** 2024-02-22 02:27 UTC
Labels: bug
